# Site
name: "Denis Vasconcelos"
title: "Denis Vasconcelos"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Denis:
    name: Denis
    display_name: "Denis Vasconcelos"    
    description: "--"    
    email: comtato@denisvasconcelos.com
    web: https://www.denisvasconcelos.com
    twitter: TrololodeMulher
    facebook: lidiane.vasconcelos.94
    image: http://Denis-Vasconcelos.github.io/foto.jpg   
    gravatar: b1f70d5531cb13d5190017257d35fab1
    description: "--"
  sal:
    name: Sal
    display_name: "Denis Vasconcelos"
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: "Denis Vasconcelos"    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache    
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Other
#=============================================
markdown: kramdown
highlighter: rouge

include: ['_pages']

permalink: /:title
page_permalink: /:title


# Verification Tokens:
#=============================================
google_verify: 6GcW4Xv_-zM0VrPiBFV6ZbRiBxTFqnqCKss0FhVpgQk
yandex_verify: d4297441f24b3cef
bing_verify: 9364933C71A3EB51D875FC6DAAC58033
pinterest_verify: 0e0e098323a2c64fb4d724141de4e72e

#Social Media
#=============================================
facebook:
  admins: lidiane.vasconcelos.94
  admin_id: 1877953365614881
  publisher: TrololoMulher
  app_id: 716605308724809
twitter:
  username:  TrololoMulher


#Icons & Colors
#=============================================
theme_color:
background_color:

#Manifest
#=============================================
manifest_name: "Denis Vasconcelos"
manifest_short_name: "Denis Vasconcelos" # Appears in "Add to home screen" dialogues and may have other importance also
manifest_lang: pt-br
manifest_background_color: white
manifest_theme_color: white
manifest_display: standalone
